tasks:
  numpy:
    name: Install numpy version
    command: python3 -m venv venv && source venv/bin/activate && python3 -m pip install numpy==2.0.0 Cython==3.0.10
    triggeredBy:
      - manual
  pypackages:
    name: Install python packages using venv
    command: source venv/bin/activate && python3 -m pip install -r env/scanvi_scib_cellrank_requirements.txt
    triggeredBy:
      - manual
  rpackages:
    name: Install R packages using Renv
    command: Rscript -e "renv::restore()"
    triggeredBy:
      - manual